/**
 * Resolve a frontend env var with priority:
 *   1. window.VITE_CONFIG (generated by docker-entrypoint at container startup)
 *   2. import.meta.env   (build-time, emitted by Vite)
 *
 * This lets a single built image be reconfigured at deploy time by setting
 * VITE_* environment variables on the container.
 */
export const getEnv = <K extends keyof ImportMetaEnv>(
  key: K
): ImportMetaEnv[K] | undefined => {
  if (typeof window !== 'undefined' && window.VITE_CONFIG?.[key]) {
    return window.VITE_CONFIG[key] as ImportMetaEnv[K]
  }
  return import.meta.env[key]
}
