# Generated by Django 5.2.9 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_active_application_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="linto_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Idempotent checkpoint of the transcription/notification "
                    "pipeline: conversation_id, per-step completion flags and "
                    "attempt count. Used to resume after a crash/retry without "
                    "re-running completed steps."
                ),
                verbose_name="LinTO pipeline state",
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("active", "Active"),
                    ("stopped", "Stopped"),
                    ("saved", "Saved"),
                    ("aborted", "Aborted"),
                    ("failed_to_start", "Failed to Start"),
                    ("failed_to_stop", "Failed to Stop"),
                    ("notification_succeeded", "Notification succeeded"),
                    ("notification_failed", "Notification failed"),
                ],
                default="initiated",
                max_length=50,
            ),
        ),
    ]
