# Generated by Django 5.2.14 on 2026-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Sits on top of the upstream 0022 so the fork keeps a single migration
        # leaf after a rebase. The file name is deliberately NOT renumbered:
        # deployed databases already recorded this migration under this name.
        ('core', '0022_user_default_room_access_level_and_more'),
    ]

    operations = [
        # ``linto_state`` may already exist on databases that applied this migration
        # under its pre-rebase name (0021_recording_linto_state_and_more) before it
        # was renumbered to 0022. A plain AddField would then crash the migrate step
        # with "DuplicateColumn: column linto_state already exists", leaving the
        # history desynced forever (and blocking every later migration). We keep the
        # Django *state* as a normal AddField but make the *database* operation
        # idempotent with ADD COLUMN IF NOT EXISTS, so migrate self-heals at deploy
        # time: a fresh database gets the column, a desynced one is a no-op, and 0022
        # is recorded as applied either way. DROP DEFAULT makes the fresh-database
        # schema identical to what Django's AddField would have produced.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='recording',
                    name='linto_state',
                    field=models.JSONField(blank=True, default=dict, help_text='Idempotent checkpoint of the transcription/notification pipeline: conversation_id, per-step completion flags and attempt count. Used to resume after a crash/retry without re-running completed steps.', verbose_name='LinTO pipeline state'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE meet_recording ADD COLUMN IF NOT EXISTS linto_state jsonb NOT NULL DEFAULT '{}';",
                        "ALTER TABLE meet_recording ALTER COLUMN linto_state DROP DEFAULT;",
                    ],
                    reverse_sql="ALTER TABLE meet_recording DROP COLUMN IF EXISTS linto_state;",
                ),
            ],
        ),
        migrations.AlterField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('active', 'Active'), ('stopped', 'Stopped'), ('saved', 'Saved'), ('aborted', 'Aborted'), ('failed_to_start', 'Failed to Start'), ('failed_to_stop', 'Failed to Stop'), ('notification_succeeded', 'Notification succeeded'), ('external_process_successful', 'External process successful'), ('external_process_failed', 'External process failed'), ('notification_failed', 'Notification failed')], default='initiated', max_length=50),
        ),
    ]
